when@dev:
  web_profiler:
    toolbar: false # DÃ©sactive la toolbar
    intercept_redirects: false

  framework:
    profiler:
      collect_serializer_data: true

when@test:
  framework:
    profiler: { collect: false }
